name: flutter_scroll_bottom_sheet
description: "This package provides a flexible bottom sheet, built on top of the flutter_appbar package, that syncs with scroll events instead of relying only on gestures."
version: 1.1.0
publisher: ttankkeo112@gmail.com
repository: https://github.com/MTtankkeo/flutter_bottom_sheet

environment:
  sdk: '>=3.4.0-163.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appbar: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: